---
title: "07 20 2020 - Rap Artists"
author: "Brett Moxham"
date: "20/07/2020"
output: html_document
---

## Libraries and Data

Data is part of the Tidy Tuesday collection. Found [here](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-04-14/readme.md).

```{r}
library(tidyverse)


polls <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-14/polls.csv')
rankings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-14/rankings.csv')

```




```{r}
rankings %>% 
  count(artist, sort = TRUE)

polls %>% 
  distinct(critic_name)

polls %>% 
  count(critic_country, sort = T)

  
polls <- polls %>% 
  separate(artist, into = c("artist", "featured"), sep = "ft. ") %>% 
  mutate(
    featured = case_when(
      featured == "Snoop Doggy Dogg" ~ "Snoop Dogg",
      TRUE ~ as.character(featured)),
      featured = str_trim(featured))



polls %>%
  filter(!is.na(featured))%>% 
  count(featured, sort = T) %>% 
  top_n(10)


plot_featured <- polls %>% 
  filter(!is.na(featured)) %>% 
  count(featured, sort = T) %>% 
  top_n(10) %>% 
  ggplot(aes(reorder(featured, n), n))+
  geom_col(fill = "firebrick")+
  coord_flip()+
  bmox::theme_bmox()+
  theme(
    axis.text.x = element_text(),
    panel.grid.major.x  = element_blank(),
    panel.grid.minor = element_blank()
    
  )+
  labs(
    y ="",
    x="",
    title = "Featured Artists",
    subtitle = "Featured Artist Mentions"
  )


plot_artist <- polls %>% 
  count(artist, sort = T) %>% 
  top_n(10) %>% 
  ggplot(aes(reorder(artist, n), n))+
  geom_col(fill = "deepskyblue")+
  coord_flip()+
  bmox::theme_bmox()+
  theme(
    #axis.text.x = element_text(),
    panel.grid.major.x  = element_blank(),
    panel.grid.minor = element_blank()
    
  )+
  labs(
    y ="",
    x="",
    title = "Main Artists",
    subtitle = "Artist Mentions"
  )


```



```{r}
rankings_sep <- rankings %>% 
    separate(artist, into = c("artist", "featured"), sep = "ft. ") %>% 
  mutate(
    featured = case_when(
      featured == "Snoop Doggy Dogg" ~ "Snoop Dogg",
      TRUE ~ as.character(featured)),
      featured = str_trim(featured))


## Artist (Jay-Z)

rankings_sep %>% 
  count(artist, sort = T) %>% 
  top_n(10)

rankings_sep %>% 
  filter(artist == "JAY-Z")


## Featured (Snoop)

rankings_sep %>% 
  filter(!is.na(featured)) %>% 
  count(featured, sort = T) %>% 
  top_n(10)

rankings_sep %>% 
  filter(featured == "Snoop Dogg")


## ARTIST PLOTS BY YEAR
artist_points <- ggplot(rankings_sep, aes(year, points, color = factor(gender),label = paste(title, artist, sep =" - ")))+
  geom_point(size = 2)+
  ggrepel::geom_text_repel(data = subset(rankings_sep, points > 50), color = "black")+
  scale_color_manual(values = c("deeppink", "lightblue3", "green"))+
  bmox::theme_bmox()+
  theme(
    panel.grid.major= element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_text(hjust = 0.1,vjust = 1, face = "bold"),
    plot.subtitle = element_text(hjust =0.1,vjust =1)
  )+
  guides(alpha = FALSE)+
  labs(
    title = "Song Points by Year",
    subtitle = "By Artist",
    y = "Song Points",
    x ="Year",
    color = "Artist Gender"
  )
  
  

##FEATURED PLOTS BY YEAR
featured_points <- rankings_sep %>% 
  filter(!is.na(featured)) %>% 
  ggplot(aes(year, points, color = gender, label = paste(title, featured, sep = " - ")))+
  geom_point(size = 2)+
  ggrepel::geom_text_repel(data = subset(rankings_sep, points > 20 & !is.na(featured)), color = "black", force = 10, size = 10)+
  #gghighlight::gghighlight(featured == "Snoop Dogg")+
  bmox::theme_bmox()+
  theme(
    panel.grid.major= element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_text(hjust = 0.1,vjust = 1, face = "bold"),
    plot.subtitle = element_text(hjust =0.1,vjust =1)
  )+
  labs(
    title = "Song Points by Year",
    subtitle = "By Featured Artist",
    y = "Song Points",
    x ="Year",
    color = "Featured Artist Gender"
  )


## Women in Rap
women_points <- rankings_sep %>%
  filter(gender == "female") %>% 
ggplot(aes(year, points, color = factor(gender), label = paste(title, artist, sep = " - ")))+
  geom_point(size = 2)+
  #gghighlight::gghighlight(gender == "female")+
  ggrepel::geom_text_repel(data = subset(rankings_sep, gender == "female", size = 25))+
  bmox::theme_bmox()+
  theme(
    panel.grid.major= element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_text(vjust = 1, face = "bold"),
    plot.subtitle = element_text(hjust =0.1,vjust =1)
  )+
  guides(color = FALSE)+
  labs(
    title = "Women in Rap",
    y = "Song Points",
    x ="Year"
  )

```


## Combining Graphs

```{r}
library(cowplot)
library(gridExtra)

full_plot_cowplot <- ggdraw()+
  draw_plot(plot_artist, x = 0, y = .5, width = .5, height = 0.5)+
  draw_plot(plot_featured, x = 0.5, y = 0.5, width = .5, height = 0.5)+
  draw_plot(women_points, x = 0, y = 0, width = 1, height = 0.5)

save_plot("Images/Rapper/07-26-2020-full_plot_cowplot.png", full_plot_cowplot, base_width = 25, base_height = 15, limitsize = FALSE)

full_plot_grid_extra <- grid.arrange(plot_artist, plot_featured,
             women_points, artist_points,
             ncol =2, nrow = 2,
            layout_matrix = rbind(c(1,2), c(3,4)))    

ggsave("Images/Rapper/07-26-2020-full_plot_grid_extra.png", full_plot_grid_extra, width = 25, height = 15)



```


